# -*- coding: utf-8 -*-
"""dashboard sederhana-seftian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pSM5MUgvAQocEs6uQGPyv7yzumODGR_A
"""

#pip install streamlit

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency

sns.set(style='dark')

st.title('E-Bike Sharing Analysis')
tab1, tab2, tab3 = st.tabs(["Tab 1", "Tab 2", "Tab 3"])
with tab1:
  st.header("Hari atau Jam dengan penyewa terbanyak?")
  st.image('https://github.com/tianiums/streamlit-example/blob/master/jam%20efektif.png')


with tab2:
  st.header("Musim Terbaik dan Cuaca yang mendukung?")
  st.image('https://github.com/tianiums/streamlit-example/blob/master/Musim%20terbaik.png')
  st.image('https://github.com/tianiums/streamlit-example/blob/master/berdasar%20cuaca.png')

with tab3:
  st.header("Workday atau Weekend yang terbanyak penyewanya?")
  st.image('https://github.com/tianiums/streamlit-example/blob/master/rata%20arat%20pemakaian.png')

